### ISSUE TITLE
No such file or directory: 'log/log_cavp_01/infos.json'

### ISSUE THREAD

**Issue by rukiye-sk** [daqingliu/CAVP#6]
Hi, 
I have the following error: 
Terminating BlobFetcher
Traceback (most recent call last):
  File "tools/train.py", line 207, in <module>
    train(opt)
  File "tools/train.py", line 58, in train
    with open(os.path.join(opt.start_from, 'infos.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'log/log_cavp_01/infos.json'

I have tried to train the network but couldn't process it because of this error. Would you help with this, please?

**Comment by daqingliu** [comment]
you can try to first remove the 'log/log_cavp_01' folder and then directly run the 'run_train.sh'.
ideally, the error will disappear.

**Comment by rukiye-sk** [comment]
Thank you for your response. However, it didn't work. I have followed all instructions and have still the same error.

**Comment by daqingliu** [comment]
emmm, actually in the first training stage, it shouldn't go to line 58 for the opt.start_from should be None.
I think you can run the following bash and tell me the output:

```
#! /bin/bash

# some parameters
model="cavp"
id="_01"
batch_size=100

# set save paths
ckpt_path="log/log_"$model$id
if [ ! -d $ckpt_path ]; then
  mkdir -p $ckpt_path
fi

# save and continue training
if [ ! -f $ckpt_path"/infos.json" ]; then
  start_from=""
else
  start_from="--start_from "$ckpt_path
fi

# first XE train
python tools/train.py --id $model$id --caption_model $model --batch_size $batch_size --save_checkpoint_every -1 --rnn_size 1300 --input_encoding_size 1000 --att_hid_size 1024 --use_bn 1 --max_epochs 37 --scheduled_sampling_start 0 --learning_rate 5e-4 --learning_rate_decay_start 0 --language_eval 1 --checkpoint_path $ckpt_path
```

**Comment by rukiye-sk** [comment]
Thank you, please see the following issues:
  File "CAVP/tools/dataloader.py", line 196, in __getitem__
    att_dict = np.load(os.path.join(self.input_att_dir, str(self.info['images'][ix]['id']) + '.npz'))
  File "lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cocotalk_box_36/368402.npz'

Before this, I had another error(convert_tsv_to_npx.py)

Traceback (most recent call last):
  File "misc/convert_tsv_to_npz.py", line 34, in <module>
    item[field] = np.frombuffer(base64.decodestring(item[field].encode()), 
  File "lib/python3.6/base64.py", line 554, in decodestring
    return decodebytes(s)
  File "lib/python3.6/base64.py", line 546, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by daqingliu** [comment]
ok... `binascii.Error: Incorrect padding` is a very generic error, it is very hard to figure out what happened. based on my experience, it may 1) tsv file damaged 2) wrong environment, e.g. change python 3 to 2?
